INSERT INTO ORDERS(ID, CUSTOMER_ID) VALUES (1, 3);
INSERT INTO ORDERS(ID, CUSTOMER_ID) VALUES (2, 4);
INSERT INTO ORDERS(ID, CUSTOMER_ID) VALUES (3, 4);
INSERT INTO ORDERS(ID, CUSTOMER_ID) VALUES (4, 3);
INSERT INTO ORDERS(ID, CUSTOMER_ID) VALUES (5, 4);
INSERT INTO ORDERS(ID, CUSTOMER_ID) VALUES (6, 3);

INSERT INTO ORDERS(ID, CUSTOMER_ID) VALUES (100, 100);