INSERT INTO SKUS(ID, DESCRIPTION) VALUES (1, 'Sample SKU #1');
INSERT INTO SKUS(ID, DESCRIPTION) VALUES (2, 'Sample SKU #2');
INSERT INTO SKUS(ID, DESCRIPTION) VALUES (3, 'Sample SKU #3');

INSERT INTO SKUS(ID,DESCRIPTION) VALUES(100, 'TEST');
